services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    command: rails s -b 0.0.0.0
    depends_on:
      - db
  db:
    image: postgres
    volumes:
      - db:/var/lib/postgresql/data2
    command: "postgres -c 'max_connections=500'"
    environment:
      POSTGRES_DB: myappdb
      POSTGRES_USER: myuser1
      POSTGRES_PASSWORD: MyUserPassword123!
    ports:
      - "5432:5432"
volumes:
  db:
    driver: local
networks:
  default:
    name: myapp_default
